{% set version = "0.1.5" %}

package:
  name: homura
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/homura/homura-{{ version }}.tar.gz
  md5: c54957da25a5a0c61a16cfa87a016c38

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - certifi
    - humanize
    - six
    - pycurl

about:
  home: https://github.com/shichao-an/homura
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Python downloader with progress'

extra:
  recipe-maintainers:
    - ocefpaf
