travis:
  secure:
    BINSTAR_TOKEN: hBX6kKZuup/SJ6kPItg0AblHkXNd15rMxGtjDNSHUe7xsS/E5SzUyf0YsmXshGK1RYH5EXISBzEx7Fh5soYu0DMHq/+k/XRC4otQfvln6wYn4xFf35EVayFEZ2yCq0W7+X71N7a9/R56cr43idjTry0zfCmK8FvYaOq/zVxqXxiw8n5SpLyL+5VcZsbPnuXvXE+etO8jWchc5A0UJib2GDek+EZXgplAwZAhD/8BRWSctoiHVPPqUUZu7zCe4pnM/WK1B6t7Y9m1/mp6rtJNr/gtXxS07F4KhxbJV5VtSZ4jgpOor+ggKt+y07f4V/G189jrDDCBnQIVW8P5dNelbeHgG0AY61fRJvNRovblXUXum5lVWeEOo4ukMxbWakd991iMZygUSugg3TO117wGUy2kX9qic10JwMGNzooPknMHdBPOKTqRcM2n7sG9AZb+lKsPmnzyWNd/aWmmmG4LIZK+FLdMeZJAnce/5iVGA9wE9B/Gfxi5bzTJ+uN+64kWWGTtRPwiaXWMLMuNYlk8lg8HgNuSwgQqqEBSWIivprxQ4VD0l5BoRbLFSYTWIhejIYsuruxwJOzVORfdT+2l5GadIsfACgSMOTz1UORnbrpYwpCFD74Q5XksApwJR7pE9WdmLILiD0FI8iglPgI6XOtgZxISla+jtiw9PT9RDzs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
