travis:
  secure:
    BINSTAR_TOKEN: zxQyiys+gpNo1b1rI51s12bdNgcXwccQZKQ783wIsWNq9PtdCFFTTCN2XFWlRMVrF8jLiHis0vMMJSeZ8YRqk5kC3eXQEJj19tfPP9rzOhKkPBsrZ1mFcNrsbW7VTYJxa7fA4nldFpjxNP5Dp0LupZ9tew/hnElB7C5xn2Q7vwdNbdB3J7OWCVrRjhZVtsEEnfuMFzeQZzIvx+8mg3g0k80SWYVUW0UQMr54IvFV4o/KIe8X6WdQPB4YPj+/hqv2nBfkIM9hwuOQOoW7dKXcqncoZSsjE6StO0usA3jxrIfMzskNl8oich/3X5esOPBHV3yD7cl+kOcYeUDzbeItrst1mu/bG8lmJpaInBO25ZfAPT+PJgJsWI2pHd9wuXxvVvoIg+UWtqJkNCQ/wOekpuMALFHfbRssxhWl17ZlEGaKDrs8h4lL9hch2O3S/uJrsGJkZZXHBmQz0xpM2y5gW63i/g7DPPbwARzwj3bCZoktZ9iMvqR/93CGr7yzB2PYB4uPXRgSiIRvO5iR0c66eKrzpu7A9nTzWMjGxHakpSaWNLU0UlPP4ejBEADUxSx6C45dwlPvGU55NpT7IbeJbv+ZRCnpmXc/SKOQpZRKDfbceXfW/rhNJB7LmlALna1a122RuWAeUCEh3AgJD0lucE37N8MjGYwI76zK9gf13M4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
